TRUNCATE TABLE EVENTS;
TRUNCATE TABLE VENUES;

ALTER SEQUENCE events_id_seq RESTART WITH 1;
ALTER SEQUENCE venues_id_seq RESTART WITH 1;

INSERT INTO venues(venue_name, street_address, city, state, zip_code, venue_type, venue_img) VALUES ('TD Pavillion | The Mann', '5201 Parkside Ave', 'Philadelphia', 'PA', '19131', 'Outdoor Music Venue & Event Space', 'https://manncenter.org/sites/default/files/styles/3_by_2_large/public/2019-10/fw8a0180.jpg');
INSERT INTO venues(venue_name, street_address, city, state, zip_code, venue_type, venue_img) VALUES ('The Fillmore', '29 E Allen St', 'Philadelphia', 'PA', '19123', 'Multi-Venue Performace & Event Space', 'https://assets.livenationcdn.com/uploads/fillmore-header.png');
INSERT INTO venues(venue_name, street_address, city, state, zip_code, venue_type, venue_img) VALUES ('Theatre of the Living Arts', '334 South St', 'Philadelphia', 'PA', '19147', 'Concert Venue', 'https://assets.livenationcdn.com/uploads/tla_1024x576.jpg');
INSERT INTO venues(venue_name, street_address, city, state, zip_code, venue_type, venue_img) VALUES ('The Moshulu', '40 S Christopher Columbus Blvd', 'Philadelphia', 'PA', '1906', 'Restaurant, Museum, & Event Vessel', 'https://fastly.4sqi.net/img/general/600x600/33940132_NS_zTQwoe3-bV0HeF4Z9Wcv-JOJOkWOHortGgno9Irc.jpg');
INSERT INTO venues(venue_name, street_address, city, state, zip_code, venue_type, venue_img) VALUES ('Lincoln Financial Field', '1 Lincoln Financial Field Way', 'Philadelphia', 'PA', '19148', 'Football Stadium', 'https://pbs.twimg.com/profile_images/1762190674877673472/OGAjE1GK_400x400.jpg');

-- TD Pavllion
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (1, 'Balletx Festival', 'Contemporary Ballet', 'BalletX', '7:30 pm', 'Saturday', 'April 27', 'https://www.westphillylocal.com/wp-content/uploads/2024/03/BalletX-Mann-Festival.jpg', 25, 133);
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (1, 'The Avett Brothers', 'Concert', 'The Avett Brothers', '7:00 pm', 'Thursday', 'May 16', 'https://manncenter.org/sites/default/files/styles/event_slideshow/public/2024-01/Avetts.png?h=57024e64', 75, 850);
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (1, 'Batman in Concert', '', 'Philadelphia Orchestra', '8:00 pm', 'Tuesday', 'June 18', 'https://manncenter.org/sites/default/files/styles/event_slideshow/public/2024-03/Batman-Event-Photo.jpg?h=8a7fc05e', 49, 189);

-- The Fillmore
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (2, 'can we start over tour', 'Concert', 'Charlotte Sands', '8:00 pm', 'Friday', 'April 5', 'https://photos.bandsintown.com/thumb/16232835.jpeg', 28, 28);
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (2, 'Unprocessed', 'Concert', 'Unprocessed', '7:30 pm', 'Tuesday', 'April 9', 'https://i.scdn.co/image/ab6761610000e5ebb311b958b8c3a7219d781979', 28, 28);
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (2, 'BLEEDERS Tour', 'Concert', 'Black Veil Brides', '7:00 pm', 'Thursday', 'May 16', 'https://cdn.shopify.com/s/files/1/0269/7045/6128/files/blackveilbridesapril2024tour_1024x1024.jpg?v=1702406528', 53, 229);
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (2, 'queer joy dance party', 'Dance Party', 'Sapphic Factory', '9:00 pm', 'Friday', 'May 17', 'https://photos.bandsintown.com/thumb/16422942.jpeg', 23, 36);

-- Theatre of the Living Arts
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (3, 'Fountain Baby Tour', 'Concert', 'Amaarae', '8:00 pm', 'Tuesday', 'March 26', 'https://cdn.theatlantic.com/thumbor/e8PUyu-a5fxMuS7F6wTllxScszU=/1368x0:4068x2700/1080x1080/media/img/mt/2023/11/Amaarea_HR/original.jpg', 45, 99);
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (3, 'The TS Dance Party', 'Dance Party', 'TSN Parties', '8:00 pm', 'Saturday', 'March 30', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCcVlKaZQBv7WrhSap89dV3v7g2QHHkl3ffIjS1C5uUzHtL-Is0AWtyRQ1msW2fhs96lI&usqp=CAU', 28, 28);
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (3, 'The Blackout Tour Pt. 2', 'Concert', 'From Ashes to New', '6:00 pm', 'Sunday', 'May 5', 'https://paramountny.com/wp-content/uploads/2024/02/FromAshesToNew-eventpage.png', 48, 65);
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (3, 'Silhouettes Tour', 'Concert', 'Prateek Kuhad', '8:00 pm', 'Wednesday', 'May 29', 'https://s1.ticketm.net/dam/a/d24/40a1e7a2-5310-45d3-a40c-ce72527d9d24_RETINA_PORTRAIT_3_2.jpg', 39, 210);

-- The Moshulu
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (4, 'Emo Night Philly', 'Dance Party', 'DJ Deejay', '10:00 pm', 'Saturday', 'May 11', 'https://pbs.twimg.com/profile_images/1263211401063075843/9AXRdU-l_400x400.jpg', 10, 20);
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (4, 'Me Porto Bonito', 'Dance Party', 'LATINVIBESGROUP', '10:00 pm', 'Saturday', 'March 30', 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F727195899%2F167022119644%2F1%2Foriginal.20240325-002713?h=2000&w=720&auto=format%2Ccompress&q=75&sharp=10&s=0545b4364eeba1756a709f4b307252bf', 12, 90);
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (4, 'Freedom Party PHL', 'Dance Party', 'Herbert Holler', '10:00 pm', 'Friday', 'April 20', 'https://s3-media0.fl.yelpcdn.com/bphoto/5cLake0e0ibEzB0TctqpzA/348s.jpg', 10, 20);
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (4, 'Cinco De Mayo Deck Party', 'Holiday Party', 'The Moshulu', '1:00 pm', 'Sunday', 'May 5', 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F727723169%2F218421661366%2F1%2Foriginal.20240325-170417?w=940&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C0%2C1920%2C960&s=62596d683a38716bd33050ba681758a2', 30, 50);

-- Lincoln Financial Field
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (5, 'WrestleMania Night 1', 'Sporting Event', 'WWE', '6:30 pm', 'Saturday', 'April 6', 'https://metro.co.uk/wp-content/uploads/2023/08/WrestleMania-40-logo-4a01.jpg?quality=90&strip=all&zoom=1&resize=480%2C270', 128, 18480);
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (5, 'WrestleMania Night 2', 'Sporting Event', 'WWE', '7:30 pm', 'Sunday', 'April 7', 'https://www.lincolnfinancialfield.com/wp-content/uploads/2023/12/CS-035419_1200x1200-e1709312622814.jpg', 128, 18480);
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (5, 'AMA Supercross Championship', 'Sporting Event', 'Monster Energy', '2:30 pm', 'Saturday', 'April 27', 'https://www.lincolnfinancialfield.com/wp-content/uploads/2023/12/23816370-SX-2024-Philadelphia-Handfinger-Static_Venue_Kit-LincolnFinancial_1200x1200-1536x1536.jpg', 33, 310);
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (5, 'NCAA Lacrosse Championships', 'Sporting Event', 'Lincoln Financial Field', '12:00 pm', 'Saturday', 'May 25', 'https://www.ncaa.com/_flysystem/public-s3/2023-06/MLAX_D1_Champ_RGB.png', 25, 272);
INSERT INTO events(venue_id, event_name, event_type, event_host, event_time, event_date, event_img, ticket_price_min, ticket_price_max) VALUES (5, 'Sun Goes Down Tour', 'Concert', 'Kenny Chesney', '5:00 pm', 'Saturday', 'June 8', 'https://www.lincolnfinancialfield.com/wp-content/uploads/2023/11/KennyChesney-ZBB-MM-UK_Social_1080x1080_0608-PhiladelphiaPA-1536x1536.jpg', 91, 1372);