# Generated by Django 5.0.3 on 2024-03-25 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(default='undefined', max_length=100)),
                ('street_address', models.CharField(default='undefined', max_length=100)),
                ('city', models.CharField(default='undefined', max_length=100)),
                ('state', models.CharField(default='undefined', max_length=100)),
                ('zip_code', models.CharField(default='undefined', max_length=100)),
                ('venue_type', models.CharField(default='undefined', max_length=200)),
                ('venue_img', models.TextField(default='undefined')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='undefined', max_length=100)),
                ('event_type', models.CharField(default='undefined', max_length=100)),
                ('event_host', models.TextField(default='undefined', max_length=100)),
                ('event_time', models.TextField(default='undefined', max_length=10)),
                ('event_date', models.TextField(default='undefined', max_length=100)),
                ('event_img', models.TextField(default='undefined')),
                ('ticket_price_min', models.IntegerField()),
                ('ticket_price_max', models.IntegerField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='tickit.venue')),
            ],
        ),
    ]
