# Generated by Django 5.0.3 on 2024-03-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_host',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='street_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_img',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='zip_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
