# Generated by Django 5.0.3 on 2024-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0003_alter_event_event_date_alter_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
