# Generated by Django 5.0.3 on 2024-03-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0004_alter_event_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='venue',
            new_name='tickit_venue',
        ),
    ]
